/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ventanas;

import javax.swing.JOptionPane;
public class jif_administrador extends javax.swing.JInternalFrame {


    public jif_administrador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label_usuario = new javax.swing.JLabel();
        input_admin_user = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        label_pass = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        label_nombre = new javax.swing.JLabel();
        input_admin_nombre = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        label_apellido = new javax.swing.JLabel();
        input_admin_apellido = new javax.swing.JTextField();
        input_admin_pass = new javax.swing.JPasswordField();
        registrar_admin = new javax.swing.JPanel();
        label_registrar_admin = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Gestion Administrador");
        setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        setVisible(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_usuario.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        label_usuario.setForeground(new java.awt.Color(0, 0, 0));
        label_usuario.setText("Usuario");
        jPanel1.add(label_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 120, 30));

        input_admin_user.setBackground(new java.awt.Color(255, 255, 255));
        input_admin_user.setForeground(new java.awt.Color(102, 102, 102));
        input_admin_user.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        input_admin_user.setText("juan_perez");
        input_admin_user.setBorder(null);
        input_admin_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                input_admin_userMouseClicked(evt);
            }
        });
        jPanel1.add(input_admin_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 390, 50));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 390, 20));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 390, 20));

        label_pass.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        label_pass.setForeground(new java.awt.Color(0, 0, 0));
        label_pass.setText("Contraseña");
        jPanel1.add(label_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 120, 30));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 390, 20));

        label_nombre.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        label_nombre.setForeground(new java.awt.Color(0, 0, 0));
        label_nombre.setText("Nombre");
        jPanel1.add(label_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 120, 30));

        input_admin_nombre.setBackground(new java.awt.Color(255, 255, 255));
        input_admin_nombre.setForeground(new java.awt.Color(102, 102, 102));
        input_admin_nombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        input_admin_nombre.setText("Juan");
        input_admin_nombre.setBorder(null);
        input_admin_nombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                input_admin_nombreMouseClicked(evt);
            }
        });
        jPanel1.add(input_admin_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 390, 50));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, 390, 20));

        label_apellido.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        label_apellido.setForeground(new java.awt.Color(0, 0, 0));
        label_apellido.setText("Apellido");
        jPanel1.add(label_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 120, 30));

        input_admin_apellido.setBackground(new java.awt.Color(255, 255, 255));
        input_admin_apellido.setForeground(new java.awt.Color(102, 102, 102));
        input_admin_apellido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        input_admin_apellido.setText("Perez");
        input_admin_apellido.setBorder(null);
        input_admin_apellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                input_admin_apellidoMouseClicked(evt);
            }
        });
        jPanel1.add(input_admin_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 390, 50));

        input_admin_pass.setBackground(new java.awt.Color(255, 255, 255));
        input_admin_pass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        input_admin_pass.setText("jPasswordField1");
        input_admin_pass.setBorder(null);
        input_admin_pass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                input_admin_passMouseClicked(evt);
            }
        });
        jPanel1.add(input_admin_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 390, 50));

        registrar_admin.setBackground(new java.awt.Color(98, 0, 238));

        label_registrar_admin.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        label_registrar_admin.setForeground(new java.awt.Color(255, 255, 255));
        label_registrar_admin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_registrar_admin.setText("Crear Nuevo Administrador");
        label_registrar_admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_registrar_adminMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout registrar_adminLayout = new javax.swing.GroupLayout(registrar_admin);
        registrar_admin.setLayout(registrar_adminLayout);
        registrar_adminLayout.setHorizontalGroup(
            registrar_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_registrar_admin, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
        );
        registrar_adminLayout.setVerticalGroup(
            registrar_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_registrar_admin, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(registrar_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, 390, 50));

        jPanel2.setBackground(new java.awt.Color(3, 218, 198));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void label_registrar_adminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_registrar_adminMouseClicked
        String user = input_admin_user.getText();
        char[] pass = input_admin_pass.getPassword();
        String nombre = input_admin_nombre.getText();
        String apellido = input_admin_apellido.getText();
        administrador admin = new administrador(user, pass, nombre, apellido);
        JOptionPane.showMessageDialog(null, "El user name es: "+admin.getUser() + " su nombre es: "+admin.getNombre()+ " "+ admin.getApellido(), "datos admin", -1);
    }//GEN-LAST:event_label_registrar_adminMouseClicked

    private void input_admin_userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_input_admin_userMouseClicked
        input_admin_user.setText(null);
    }//GEN-LAST:event_input_admin_userMouseClicked

    private void input_admin_passMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_input_admin_passMouseClicked
        input_admin_pass.setText(null);
    }//GEN-LAST:event_input_admin_passMouseClicked

    private void input_admin_nombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_input_admin_nombreMouseClicked
        input_admin_nombre.setText(null);
    }//GEN-LAST:event_input_admin_nombreMouseClicked

    private void input_admin_apellidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_input_admin_apellidoMouseClicked
       input_admin_apellido.setText(null);
    }//GEN-LAST:event_input_admin_apellidoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField input_admin_apellido;
    private javax.swing.JTextField input_admin_nombre;
    private javax.swing.JPasswordField input_admin_pass;
    private javax.swing.JTextField input_admin_user;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel label_apellido;
    private javax.swing.JLabel label_nombre;
    private javax.swing.JLabel label_pass;
    private javax.swing.JLabel label_registrar_admin;
    private javax.swing.JLabel label_usuario;
    private javax.swing.JPanel registrar_admin;
    // End of variables declaration//GEN-END:variables
}
