/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ventanas;

import javax.swing.JOptionPane;
public class jif_cliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form jif_cliente
     */
    public jif_cliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        client_nombre_input = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        client_apellido_input = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        client_direccion_input = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        btn_client_panel = new javax.swing.JPanel();
        btn_client_label = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setBorder(null);
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Gestion Cliente");
        setPreferredSize(new java.awt.Dimension(712, 571));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        client_nombre_input.setBackground(new java.awt.Color(255, 255, 255));
        client_nombre_input.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        client_nombre_input.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        client_nombre_input.setText("Juan");
        client_nombre_input.setBorder(null);
        client_nombre_input.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                client_nombre_inputMouseClicked(evt);
            }
        });
        client_nombre_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client_nombre_inputActionPerformed(evt);
            }
        });
        jPanel1.add(client_nombre_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 390, 50));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 153, 390, -1));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Nombre");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 66, 120, 30));

        client_apellido_input.setBackground(new java.awt.Color(255, 255, 255));
        client_apellido_input.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        client_apellido_input.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        client_apellido_input.setText("Perez");
        client_apellido_input.setBorder(null);
        client_apellido_input.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                client_apellido_inputMouseClicked(evt);
            }
        });
        client_apellido_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client_apellido_inputActionPerformed(evt);
            }
        });
        jPanel1.add(client_apellido_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 390, 50));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 390, -1));

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Apellido");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 120, 30));

        client_direccion_input.setBackground(new java.awt.Color(255, 255, 255));
        client_direccion_input.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        client_direccion_input.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        client_direccion_input.setText("Calle Falsa 123");
        client_direccion_input.setBorder(null);
        client_direccion_input.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                client_direccion_inputMouseClicked(evt);
            }
        });
        client_direccion_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client_direccion_inputActionPerformed(evt);
            }
        });
        jPanel1.add(client_direccion_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 390, 50));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, 390, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Direccion");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 120, 30));

        btn_client_panel.setBackground(new java.awt.Color(98, 0, 238));
        btn_client_panel.setForeground(new java.awt.Color(98, 0, 238));

        btn_client_label.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btn_client_label.setForeground(new java.awt.Color(255, 255, 255));
        btn_client_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_client_label.setText("Crear Cliente");
        btn_client_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_client_labelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btn_client_panelLayout = new javax.swing.GroupLayout(btn_client_panel);
        btn_client_panel.setLayout(btn_client_panelLayout);
        btn_client_panelLayout.setHorizontalGroup(
            btn_client_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_client_label, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
        );
        btn_client_panelLayout.setVerticalGroup(
            btn_client_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_client_label, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(btn_client_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, 390, 50));

        jPanel2.setBackground(new java.awt.Color(3, 218, 198));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void client_nombre_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_client_nombre_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_client_nombre_inputActionPerformed

    private void client_apellido_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_client_apellido_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_client_apellido_inputActionPerformed

    private void client_direccion_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_client_direccion_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_client_direccion_inputActionPerformed

    private void client_nombre_inputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_client_nombre_inputMouseClicked
        client_nombre_input.setText(null);
    }//GEN-LAST:event_client_nombre_inputMouseClicked

    private void client_apellido_inputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_client_apellido_inputMouseClicked
        client_apellido_input.setText(null);
    }//GEN-LAST:event_client_apellido_inputMouseClicked

    private void client_direccion_inputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_client_direccion_inputMouseClicked
       client_direccion_input.setText(null);
    }//GEN-LAST:event_client_direccion_inputMouseClicked

    private void btn_client_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_client_labelMouseClicked
        String nombre = client_nombre_input.getText();
        String apellido = client_apellido_input.getText();
        String direccion = client_direccion_input.getText();
        cliente cliente = new cliente(nombre, apellido, direccion);
        JOptionPane.showMessageDialog(null, "El nombre del cliente es: "+cliente.getNombre()+" "+cliente.getApellido()+" este vive en "+cliente.getDireccion(), "Cliente", -1);
        
    }//GEN-LAST:event_btn_client_labelMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_client_label;
    private javax.swing.JPanel btn_client_panel;
    private javax.swing.JTextField client_apellido_input;
    private javax.swing.JTextField client_direccion_input;
    private javax.swing.JTextField client_nombre_input;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
